name: CI on push

on:
  push:
    branches: [ main ]
    
jobs:
  run:
    runs_on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@master
      with:
        python-version: 3.8.10
    - run: |
        pip install coverage
        coverage run -m unittest discover src/test
    - uses: codecov/codecov-action@v1
